<?php

namespace Dizda\Bundle\BlockchainBundle\Command;

use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Filesystem\LockHandler;

class BlockchainMonitorCommand extends ContainerAwareCommand
{
    /**
     * @var LoggerInterface
     */
    protected $logger;

    /**
     * {@inheritdoc}
     */
    protected function configure()
    {
        $this
            ->setName('dizda:blockchain:monitor')
            ->setDefinition(array(
                new InputArgument('Monitor addresses')
            ))
            ->setDescription('Monitor addresses')
            ->setHelp(<<<EOF
The <info>%command.name%</info> command clears the application cache for a given environment
and debug mode:

coucou

<info>php %command.full_name% --env=dev</info>
<info>php %command.full_name% --env=prod --no-debug</info>

EOF
            )
        ;
    }

    public function initialize(InputInterface $input, OutputInterface $output)
    {
        parent::initialize($input, $output); // TODO: Change the autogenerated stub

        $this->logger = $this->getContainer()->get('logger');
    }

    /**
     * {@inheritdoc}
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $lock = new LockHandler($this->getName());
        if (!$lock->lock()) {
            $this->logger->critical(sprintf('LOCKED: The command "%s" is already running in another process.', $this->getName()));

            return 0;
        }

        $blockchain = $this->getContainer()->get('dizda_blockchain.blockchain.manager');
        $blockchain->monitor();
    }
}
