<?php

namespace Dizda\Bundle\AppBundle\Repository;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;

/**
 * DepositRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepositRepository extends EntityRepository
{

    /**
     * @return ArrayCollection
     */
    public function getOpenDeposits()
    {
        $qb = $this->createQueryBuilder('d')
            ->addSelect('a')
            ->addSelect('t')
            ->innerJoin('d.addressExternal', 'a')
            ->leftJoin('a.transactions', 't')
            ->andWhere('d.isFulfilled = 0')
        ;

        return $qb->getQuery()->execute();
    }

}
