<?php

namespace Dizda\Bundle\AppBundle\Repository;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * DepositRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepositRepository extends EntityRepository
{

    /**
     * @return ArrayCollection
     */
    public function getOpenDeposits()
    {
        $qb = $this->createQueryBuilder('d')
            ->addSelect('a')
            ->addSelect('t')
            ->innerJoin('d.addressExternal', 'a')
            ->leftJoin('a.transactions', 't')
            ->andWhere('d.isFulfilled = 0')
        ;

        return $qb->getQuery()->execute();
    }

    /**
     * @param array $filters
     *
     * @return Pagerfanta
     */
    public function getDeposits(array $filters)
    {
        $qb = $this->createQueryBuilder('d')
            ->addSelect('a')
            ->addSelect('t')
            ->innerJoin('d.addressExternal', 'a')
            ->leftJoin('a.transactions', 't')
            ->orderBy('d.createdAt', 'DESC')
        ;

        $pagerfanta = (new Pagerfanta(new DoctrineORMAdapter($qb)))
            ->setMaxPerPage($filters['maxPerPage'])
            ->setCurrentPage($filters['currentPage'])
        ;

        return $pagerfanta;
    }

}
