<?php

namespace Dizda\Bundle\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DepositRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepositRepository extends EntityRepository
{
}
