<?php

namespace Dizda\Bundle\AppBundle\Repository;

use Dizda\Bundle\AppBundle\Entity\Application;
use Dizda\Bundle\AppBundle\Entity\Keychain;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;

/**
 * WithdrawOutputRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WithdrawOutputRepository extends EntityRepository
{

    /**
     * @param Application $application
     *
     * @return mixed
     *
     * @deprecated Use getWhereWithdrawIsNullByKeychain() instead
     */
    public function getWhereWithdrawIsNullByApplication(Application $application)
    {
        $qb = $this->createQueryBuilder('wo')
            ->andWhere('wo.application = :application')
            ->andWhere('wo.withdraw is NULL')
            ->andWhere('wo.isAccepted = true')
            ->setParameter('application', $application)
        ;

        return $qb->getQuery()->execute();
    }

    /**
     * @param Keychain $keychain
     *
     * @return array
     */
    public function getWhereWithdrawIsNull(Keychain $keychain)
    {
        $qb = $this->createQueryBuilder('wo')
            ->innerJoin('wo.application', 'a')
            ->andWhere('a.keychain = :keychain')
            ->andWhere('wo.withdraw is NULL')
            ->andWhere('wo.isAccepted = true')
            ->setParameter('keychain', $keychain)
        ;

        return $qb->getQuery()->execute();
    }

    /**
     * @param Application $application
     *
     * @return mixed
     */
    public function getWithdrawOutputs(Application $application = null)
    {
        $qb = $this->createQueryBuilder('wo')
            ->orderBy('wo.createdAt', 'DESC')
            ->setMaxResults(50)
        ;

        if ($application) {
            $qb->andWhere('wo.application = :application');
            $qb->setParameter('application', $application);
        }

        return $qb->getQuery()->execute();
    }

}
