<?php

namespace Dizda\Bundle\AppBundle\Repository;

use Dizda\Bundle\AppBundle\Entity\Application;
use Dizda\Bundle\AppBundle\Entity\Keychain;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;

/**
 * WithdrawOutputRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WithdrawOutputRepository extends EntityRepository
{

    /**
     * @param Keychain $keychain
     *
     * @return array
     */
    public function getWhereWithdrawIsNull(Keychain $keychain)
    {
        $qb = $this->createQueryBuilder('wo')
            ->innerJoin('wo.application', 'a')
            ->andWhere('a.keychain = :keychain')
            ->andWhere('wo.withdraw is NULL')
            ->andWhere('wo.isAccepted = true')
            ->orderBy('wo.id', 'asc')
            ->setParameter('keychain', $keychain)
        ;

        if ($maxOutputs = $keychain->getGroupWithdrawsByQuantity()) {
            // Group the withdraw with the amount of output specified
            $qb->setMaxResults($maxOutputs);
        }

        return $qb->getQuery()->execute();
    }

    /**
     * @param array $filters
     *
     * @return mixed
     */
    public function getWithdrawOutputs(array $filters)
    {
        $qb = $this->createQueryBuilder('wo')
            ->orderBy('wo.createdAt', 'DESC')
            ->setMaxResults(50)
        ;

        if ($filters['application_id']) {
            $qb->andWhere('wo.application = :application');
            $qb->setParameter('application', $filters['application_id']);
        }

        return $qb->getQuery()->execute();
    }

}
