<?php

namespace Dizda\Bundle\AppBundle\Repository;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityRepository;

/**
 * WithdrawRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WithdrawRepository extends EntityRepository
{

    /**
     * @return ArrayCollection
     */
    public function getUnsignedWithdraw()
    {
        $qb = $this->createQueryBuilder('w')
            ->innerJoin('w.withdrawInputs', 'wi')
            ->innerJoin('w.withdrawOutputs', 'wo')
            ->andWhere('w.withdrawedAt is NULL')
            ->andWhere('wo.isAccepted = true')
        ;

        return $qb->getQuery()->execute();
    }

}
